KOBO_API_URL = "https://kf.kobotoolbox.org"
KOBO_API_CSV = "https://kf.kobotoolbox.org/api/v2/assets/acEkyUMrrYvpxygUB7zRVu/export-settings/esEB3YqiFwt6r287jawXaN9/data.csv"
KOBO_API_JSON = "https://kf.kobotoolbox.org/api/v2/assets/acEkyUMrrYvpxygUB7zRVu/export-settings/esEB3YqiFwt6r287jawXaN9/data.json"
KOBO_API_XLS = "https://kf.kobotoolbox.org/api/v2/assets/acEkyUMrrYvpxygUB7zRVu/export-settings/esEB3YqiFwt6r287jawXaN9/data.xlsx"
KOBO_ASSET_UID = "acEkyUMrrYvpxygUB7zRVu"
KOBO_API_TOKEN = "6f8e7140c1b5da02e799ab608c28da997ac8acba"
